version: "3"

services:

  gate:
    build: k8s/gate
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    labels:
      dev.okteto.com/auto-ingress: domain
      dev.okteto.com/custom-domain: true
      dev.okteto.com/domain: cloud.tact.run

  web:
    build:
      dockerfile: k8s/web/Dockerfile
      context: .
      args:
        - token=${FONTAWESOME_TOKEN}
    ports:
      - "3000"
    volumes:
      - .:/src
