name: Define notification message
description: Identify an appropriate notification message.
branding:
  icon: 'message-square'
  color: 'green'
outputs:
  actor:
    description: The message sender.
    value: GitHub Actions
  color:
    description: The message color.
    value: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
  icon:
    description: The message icon.
    value: https://github.com/github.png?size=64
  txt:
    description: The message.
    value: ${{ steps.message.outputs.txt }}
  footer:
    description: The message footer.
    value: made with ❤️ for everyone by OctoLab
runs:
  using: composite
  steps:
    - name: Define notification message
      id: message
      run: |
        if [ '${{ github.event.head_commit.message != null }}' == 'true' ]
        then
          (cat <<-message
        txt=${{ github.event.head_commit.message }}
        message
        ) | head -1 >> $GITHUB_OUTPUT

        elif [ '${{ github.event.inputs.reason != null }}' == 'true' ]
        then
          (cat <<-message
        txt=${{ github.event.inputs.reason }}
        message
        ) | head -1 >> $GITHUB_OUTPUT

        elif [ '${{ github.event.schedule != null }}' == 'true' ]
        then
          echo txt='regular healthcheck' >> $GITHUB_OUTPUT
        else
          echo Cannot define notification message && exit 1
        fi
      shell: bash
