name: continuous delivery (docker)

on:
  workflow_dispatch:
  push:
    branches: [ prod ]
    paths:
      - .github/workflows/cd.docker.yml
      - k8s/app/Dockerfile
      - .dockerignore
      - .babelrc
      - .eslintrc.json
      - .npmrc
      - .prettierrc
      - package*.json
      - '**.js'
      - '**.ts'
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v4
        with: { images: ghcr.io/tact-app/frontend }
        id: metadata
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: k8s/app/Dockerfile
          build-args: token=${{ secrets.FONTAWESOME_TOKEN }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

  notify:
    runs-on: ubuntu-latest
    needs: [ deploy ]

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '🐳 ${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
