name: continuous delivery (vercel)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/cd.vercel.yml
      - package*.json
      - '**.js'
      - '**.ts'
    tags: [ '!*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'kamilsk'

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: 16, cache: npm }

      - run: npm install --global vercel@latest

      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: [ deploy ]

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '⚓️️ ${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
