name: checking

on:
  pull_request:
    branches: [ '*' ]
    paths:
      - '.github/workflows/ci.yml'
      - '**.js'
      - '**.ts'
      - 'package*.json'
  push:
    branches: [ '*' ]
    paths:
      - '.github/workflows/ci.yml'
      - '**.js'
      - '**.ts'
      - 'package*.json'
    tags: [ '!*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: 16, cache: npm }
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      # todo:review: https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

      - run: npm ci --include=dev
        env: { FONTAWESOME_NPM_AUTH_TOKEN: '${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}' }
      - run: npm run build

  # temporary solution for https://vercel.com/guides/why-aren-t-commits-triggering-deployments-on-vercel
  # see https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
  deploy:
    needs: [ build ]
    if: github.event_name == 'push' && github.actor != 'kamilsk' && success()
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: 16, cache: npm }

      - run: npm install --global vercel@latest

      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  notify:
    needs: [ build ]
    if: github.event_name == 'push' && (failure() || success())
    runs-on: ubuntu-latest

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
