name: dependabot

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - run: |
          # gh gist view --raw e09e1ecd76d5573e0517a7622009f06f | bash

          curl -fsSL https://gist.githubusercontent.com/mattt/e09e1ecd76d5573e0517a7622009f06f/raw/ed1d54acd46bdeacac8519233b32f96b40b71cca/install.sh | bash

          dependabot update -f .github/dependabot.weekend.yaml --dry-run ${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [ check ]
    runs-on: ubuntu-latest

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
